# Generated by Django 3.0.3 on 2020-02-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('food_or_cash', models.CharField(choices=[('Cash', 'Cash'), ('Food', 'Food for 150 people')], max_length=4)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iftar.Need')),
            ],
        ),
    ]
