# Generated by Django 3.0.3 on 2020-02-16 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iftar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='food_or_cash',
            field=models.CharField(choices=[('Cash', 'I will give cash and the mosque will arrange food for Iftar.'), ('Food', 'I will bring food for about 120 people for Iftar.')], max_length=4),
        ),
        migrations.AlterField(
            model_name='donor',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iftar.Need', unique=True),
        ),
    ]
